name: Publish Internal Release

on:
  push:
#     types: [ prereleased ]
    branches: [ actions-test ]

jobs:
#   analysis:
#     runs-on: ubuntu-latest

#     container:
#       image:  cirrusci/flutter:latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Print Dart SDK version
#         run: dart --version
      
#       - name: Print Flutter SDK version
#         run: flutter --version

#       - name: Analyze project source
#         run: flutter analyze

#       - name: Run tests
#         run: flutter test

  publish:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:latest

    steps:        
      - uses: actions/checkout@v2

      - name: Pub get
        run: flutter pub get
      
      - name: Build
        run: flutter build apk
        
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env: 
          BUILD_TOOLS_VERSION: "30.0.2"
      
      - name: Publish
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          packageName: com.whisperingmule.mule
          releaseFile: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: internal
          inAppUpdatePriority: 2
          whatsNewDirectory: distribution/whatsnew
          mappingFile: build/app/outputs/mapping/release/mapping.txt
        
        
